### ISSUE TITLE
Did you ever study the topics you try to approach on your project ?

### ISSUE THREAD

**Issue by pvgmenegasso** [rightvaluestest/rightvalues-old#12]
Seriously dude, wtf is this test I just did, and what in the world are these descriptions ?
You should really focus your efforts into actually putting some tought on the human part of your project. It is not enough to only make a well scripted program, with accurate maths, if you can't even basically understand the concepts you are trying to evaluate.
The descriptions you give for the ideologies seem like they're straight out of a conspiracy theory handbook. Anarcho-Primitivism is "people who think you'd be happier living in the stone age" ?
Most of this quizz could just be renamed to:
"are you a facist and/or a biggot ?"
It seems there are no questions related to actual market or governmental dynamics whatsoever, and, instead, only questions about hate, prejudice and discrimination.
"do you believe your race is superior ?"
I don't even understand why would anyone ask this question ever. This simply isn't something that is even open to debate.
Please, consider improving your humanities skills or just take the whole quiz out of the web, to save people their time.

**Comment by therightcafe** [comment]
Theres a few issues with this. First of all, the cringe inducing shit is in the process of being removed. I have modified another test and there was alot of shit left over from it, especially the racial shit.

**Comment by therightcafe** [comment]
Also I have intentionally chosen to mock certain ideologies like Neoliberalism. This was a test I made for a shitposting server on discord and I was considering implementing inside jokes in it but decided against it.

**Comment by rightvaluestest** [comment]
it was originally a project for me just for fun. Of course, I will try to
improve this test. Please state how this can be improved specifically, like
how I should word it. I will try to fix it asap.

**Comment by rightvaluestest** [comment]
I changed the wording of most questions. Tell me if there's anything to change.
