### ISSUE TITLE
Question Typos

### ISSUE THREAD

**Issue by joegrimer** [rightvaluestest/rightvalues-old#15]
Cool Quiz. This contrasts well to the leftist version. Some minor criticisms:

"A crackdown of pornography is beneficial to society" should be "A crackdown **on** pornography is beneficial to society"

Due to the fact that the action of joining a corporation is voluntary, there isn't true oppression within corporations.
could be written more concisely as:
Because joining a corporation is voluntary, there isn't true oppression within corporations.

A Good Leader should have the ability to pass on the throne to their family members
"Good" and "Leader" shoudn't be capitalised.

I am happy to add these as a commit if whoever's in charge reckons these are fair.

**Comment by rightvaluestest** [comment]
thanks, I fixed them :)
