### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by calcnerd256** [rightvaluestest/rightvalues-old#2]
The following links point to comments that quote misspelled words:
https://github.com/rightvaluestest/rightvaluestest.github.io/commit/6b6218001d91d5ff1083edccce3ec89e407e829e#r37971440
https://github.com/rightvaluestest/rightvaluestest.github.io/commit/8547b0430197fbd1452a191bbecb4ed70e5e4b91#r37971430
https://github.com/rightvaluestest/rightvaluestest.github.io/commit/4b20792a06d6e4e440fffe3b19278c4fe11adba1#r37971387
https://github.com/rightvaluestest/rightvaluestest.github.io/commit/03d4c835e09e23b8088533d0d426971a332b0f7b#r37971421

**Comment by rightvaluestest** [comment]
Should be fixed now.
