### ISSUE TITLE
Remove LeftValues Statcounter code

### ISSUE THREAD

**Issue by LeftValues** [rightvaluestest/rightvalues-old#5]
A number of the HTML files for this test have not had the LeftValues Statcounter code removed. I'd appreciate if these could be removed or replaced with your own Statcounter code.

**Comment by rightvaluestest** [comment]
Alright, I will remove it.

**Comment by rightvaluestest** [comment]
Sorry for asking, but what is the Statcounter code specifically? Is it required for the test to function? (I need to know if I need to replace it or not). Thanks in advance.

**Comment by LeftValues** [comment]
No, it just tracks the number of people who visited the website.

**Comment by rightvaluestest** [comment]
Ok. I will work on it later today.

**Comment by rightvaluestest** [comment]
I think it would be done now. Please comment if the stat-counter is still not removed.

**Comment by LeftValues** [comment]
There appears to still be statcounter code in authresults.html and libresults.html, but otherwise it is good.
